version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "5000:80"  # Maps host port 5000 to container port 80
    depends_on:
      - mongodb
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MONGODB_CONNECTIONSTRING: mongodb://mongodb:27017/slotMachine

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"  # Expose MongoDB on the default port
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
